### ISSUE TITLE
Parallelization with RELIC

### ISSUE THREAD

**Issue by codedust** [encryptogroup/ENCRYPTO_utils#23]
Is there a concrete reason for the introduction of the `relic_mutex` mutex alongside the change to RELIC in commit 7cb1b7ec82f264223735fd2193237fac1951ca0e? This practically linearizes the code when trying to parallelizing it with, e.g., OpenMP. Could this mutex be removed?

https://github.com/encryptogroup/ENCRYPTO_utils/blob/a596166d9ebdc506d1ecb2394fac5ee5d598297b/src/ENCRYPTO_utils/crypto/ecc-pk-crypto.h#L37

**Comment by MartKro** [comment]
First of all sorry for not replying earlier. I just forgot to do so when I first saw the issue.

The reason this mutex exists is to prevent (!) concurrent acceses to the relic library, since I expected somebody would try to use the library in paralell.

The issue arrises because the relic library uses global memory in the framework which for that reason concurrent access would result in data races. The library provides setter and getter for the global memory so I use this such that the relic wrapper class saves the 'current' pointer of the global memory at the instanciation of the wrapper and sets it to it's last known pointer when the wrapper is called. However, it would introduce data races if the change of the state isn't thread-safe so only one object can access the relic library at one time.

Sadly there isn't an easy fix for that. The best alternative that's come to my mind is to instanciate the library multiple times. There might be some use of the relic_mutex which I'm not sure are necersarry, but I cannot guarantee the correct behaviour of the wrapper anymore then.

**Comment by lenerd** [comment]
It is possible to enable multithreading support via CMake flags:

https://github.com/relic-toolkit/relic/blob/f93e1524fb4e234555a9f7a02b12b7be197d9acf/CMakeLists.txt#L109-L113

If `MULTI=PTHREAD`, then the global context variables are declared as thread-local:

https://github.com/relic-toolkit/relic/blob/60ddeadbe84d1caa22f851f88031b20409aa2a06/src/relic_core.c#L78-L92

**Comment by MartKro** [comment]
Good catch. My implementation regarding paralellization is likely garbage and should be redone. I will fix that until the end of the next week.

**Comment by codedust** [comment]
Removing the mutexes did the trick and is save since `first_ctx` and `core_ctx` are decleared `threadprivate` for OpenMP (equivalent to what @lenerd pointed out for pthreads):

https://github.com/relic-toolkit/relic/blob/60ddeadbe84d1caa22f851f88031b20409aa2a06/src/relic_core.c#L94-L96

I've removed all the mutexes in #25.
